version: '3.2'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "python manage.py wait_for_db && python manage.py migrate && python manage.py migrate && python
      manage.py makemigrations && gunicorn core.wsgi --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - /Users/kunwarharsh/Desktop/DjangoPrjs/drf_api_documention/django_rest_api_documentation/core:/core
    environment:
      - SECRET_KEY="${SECRET_KEY}"
      - DEBUG="${DEBUG}"
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    container_name: postgres_db
